using System;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MVCClient.Controllers
{
    [Controller]
    public class StatisticsController : Controller
    {
        [HttpGet("/v1/Statistics")]
        public IActionResult Statistics()
        {
            return View();
        }

        [HttpGet("/v1/Statistics/{websiteId}/{type}/{month}/{year}")]
        public async Task<string> GetStatistics(Guid websiteId, string type, int month, int year)
        {
            var content = new[]
            {
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 1, 11).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 2, 12).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 3, 13).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 4, 14).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 5, 15).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 6, 16).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 7, 17).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 8, 18).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 9, 19).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 10, 20).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 11, 21).ToShortDateString()},
                new {id = Guid.NewGuid(), value = 99.99, type = "Money", date = new DateTime(2021, 12, 22).ToShortDateString()}
            };

            var result = new
                {content = content, statusCode = 200, succeeded = true, title = "Statistics were reached."};

            return JsonSerializer.Serialize(result);
        }
    }
}